### ISSUE TITLE
Question regarding defining grammer for time series

### ISSUE THREAD

**Issue by xgdgsc** [sisl/GrammarExpts.jl#1]
Thank you for developing this package. I want to optimize to show expressions of combinations on some of my defined functions that operates on timeseries. The documentation on the rules provides a simple Real example. I took a look at the creatre_grammer() function defined in ACASXProblem, but it seems too complicated for me to understand. Is there a simpler example to look at for working with grammer of time series data?

**Comment by rcnlee** [comment]
This package is largely deprecated and replaced by the newer set of packages: [ExprOptimization.jl](https://github.com/sisl/ExprOptimization.jl), [ExprRules.jl](https://github.com/sisl/ExprRules.jl), and [GBDTs.jl](https://github.com/sisl/GBDTs.jl).

What specific functionality are you looking for?

GBDTs.jl has a time series example that classifies the australian sign language example from our paper.  Unfortunately it hasn't been updated to Julia 0.7/1.0, but you can still look at the syntax if you're just interested in using it with ExprOptimization.jl.  I will work on getting it updated tomorrow.

**Comment by xgdgsc** [comment]
Thanks. That' s defnitely a better example for me, I will try and see.

**Comment by xgdgsc** [comment]
I cannot get MultivariateTimeSeries working, it shows error : 
```
┌ Info: Precompiling MultivariateTimeSeries [8440422c-9f18-54da-a87b-878a663ddc15]
└ @ Base loading.jl:1192
ERROR: LoadError: invalid using path: "printtable" does not name a module
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1044
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:393
 [7] top-level scope at ./none:3
in expression starting at /home/gsc/.julia/dev/MultivariateTimeSeries/src/MultivariateTimeSeries.jl:11
Failed to precompile MultivariateTimeSeries [8440422c-9f18-54da-a87b-878a663ddc15] to /home/gsc/.julia/compiled/v1.0/MultivariateTimeSeries/rcZHf.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:311 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1190
 [4] macro expansion at ./logging.jl:309 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:947
 [6] require(::Base.PkgId) at ./loading.jl:858
 [7] require(::Module, ::Symbol) at ./logging.jl:309
 [8] top-level scope at In[31]:1

```
It' s hard to continue without knowing the data structure of input.

**Comment by rcnlee** [comment]
@xgdgsc I just pushed updates to all four packages: ExprRules.jl, ExprOptimization.jl, GBDTs.jl, and MultivariateTimeSeries.jl.  The first two are registered and I requested a minor release.  You may need to grab master if those haven't been approved yet.   Can you see if that fixes things for you?

**Comment by xgdgsc** [comment]
Thanks. No problems for now.
